/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javax.swing.JOptionPane;
import model.Jugador;
import model.SistemaDeJuego;

/**
 *
 * @author 50672
 */
public class VentanaRifaDados extends javax.swing.JFrame {
    SistemaDeJuego sistema;
    int jugadorActual = 0;
    private ArrayList<Integer> lista;
    /**
     * Creates new form VentanaRifaDados
     */
    public VentanaRifaDados(SistemaDeJuego sistema) {
        this.sistema = sistema;
        lista = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTurno = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTurno.setForeground(new java.awt.Color(0, 0, 0));
        lblTurno.setText("Turno del jugador #");
        jPanel1.add(lblTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        lblNum.setForeground(new java.awt.Color(0, 0, 0));
        lblNum.setText("1");
        jPanel1.add(lblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 20, -1));

        btnSiguiente.setText("Lanzar dados");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backgroudp.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        Random random = new Random();
        int dado1 = random.nextInt(6)+1;
        int dado2 = random.nextInt(6)+1;
        JOptionPane.showMessageDialog(this, "El jugador obtuvo " + (dado1+dado2), "Dados", 1);
        lista.add(dado1+dado2);
        if (++jugadorActual == sistema.getCantJugadores()){
            for (int i = 0; i < sistema.getCantJugadores(); i++) {
                sistema.getJugadores().get(i).num = lista.get(i);
                System.out.println(sistema.getJugadores().get(i).num);
            }
            System.out.println("");
            Collections.sort(lista);
            Collections.reverse(lista);
            for (int i = 0; i < sistema.getCantJugadores(); i++) {
                System.out.println(lista.get(i));
            }
            System.out.println("");
            ArrayList<Jugador> jug = new ArrayList<>();
            for (int i = 0; i < sistema.getCantJugadores(); i++) {
                Jugador j = sistema.returnJugador(lista.get(i));
                jug.add(j);
            }
            sistema.setJugadores(jug);
            String result = "";
            for (int i = 0; i < sistema.getCantJugadores(); i++) {
                System.out.println(sistema.getJugadores().get(i).getFicha());
                System.out.println(sistema.getJugadores().get(i).num);
                System.out.println("");
                result += "Posicion " + (i+1) + ": " + sistema.getJugadores().get(i).getFicha() + "\n";
                
            }
            JOptionPane.showMessageDialog(this, result, "Orden", 1);
            new VentanaJuego(sistema).setVisible(true);
            this.dispose();
        }
        lblNum.setText(Integer.toString(jugadorActual + 1));
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblTurno;
    // End of variables declaration//GEN-END:variables
}
