/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import model.SistemaDeJuego;
import java.util.Random;
import java.util.Collections;
import javax.swing.JOptionPane;
import model.Jugador;
/**
 *
 * @author 50672
 */
public class VentanaRifaNum extends javax.swing.JFrame {
    SistemaDeJuego sistema;
    int jugadorActual = 0;
    private ArrayList<Integer> lista;
    /**
     * Creates new form VentanaRifaNum
     */
    public VentanaRifaNum(SistemaDeJuego sistema) {
        initComponents();
        this.sistema = sistema;
        lista = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txfNum = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        lblNum = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txfNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 80, 30));

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 120, -1));

        lblNum.setForeground(new java.awt.Color(0, 0, 0));
        lblNum.setText("1");
        jPanel1.add(lblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 20, -1));

        lblTurno.setForeground(new java.awt.Color(0, 0, 0));
        lblTurno.setText("Turno del jugador #");
        jPanel1.add(lblTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/backgroudp.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        lista.add(Integer.parseInt(txfNum.getText()));
        if (++jugadorActual == sistema.getCantJugadores()){
            Random random = new Random();
            int num = random.nextInt(1000);
            System.out.println(num);
            for (int i = 0; i < sistema.getCantJugadores(); i++) {
                lista.set(i, Math.abs(lista.get(i)-num));
                sistema.getJugadores().get(i).num = lista.get(i);
                System.out.println(sistema.getJugadores().get(i).num);
            }
            Collections.sort(lista);
            ArrayList<Jugador> jug = new ArrayList<>();
            for (int i = 0; i < sistema.getCantJugadores(); i++) {
                Jugador j = sistema.returnJugador(lista.get(i));
                jug.add(j);
            }
            sistema.setJugadores(jug);
            String result = "El numero aleatorio seleccionado fue " + num + "\n";
            for (int i = 0; i < sistema.getCantJugadores(); i++) {
                System.out.println(sistema.getJugadores().get(i).getFicha());
                System.out.println(sistema.getJugadores().get(i).num);
                System.out.println("");
                result += "Posicion " + (i+1) + ": " + sistema.getJugadores().get(i).getFicha() + " y la diferencia es de " + sistema.getJugadores().get(i).num + "\n";
            }
            JOptionPane.showMessageDialog(this, result, "Orden", 1);
            new VentanaJuego(sistema).setVisible(true);
            this.dispose();
        }
        lblNum.setText(Integer.toString(jugadorActual + 1));
        txfNum.setText("");
    }//GEN-LAST:event_btnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JTextField txfNum;
    // End of variables declaration//GEN-END:variables
}
