/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.GrafoMatriz;
import model.SistemaDeJuego;
import model.Tablero;

/**
 *
 * @author 50672
 */
public class VentanaCreacionGrafo extends javax.swing.JFrame {
    ArrayList<JTextField> textfields;
    SistemaDeJuego sistema;
    /**
     * Creates new form VentanaCreacionGrafo
     */
    public VentanaCreacionGrafo(SistemaDeJuego sistema) {
        textfields = new ArrayList<JTextField>();
        this.sistema = sistema;
        System.out.println(sistema.getCantJugadores());
        initComponents();
        generateTextFields(sistema.getTablero().getGrafo().getMax());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnListo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(51, 102, 255));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));

        jLabel1.setText("Ingrese 1 si hay camino entre los vertices si no conserve el 0");

        btnListo.setText("LISTO!");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        jButton1.setText("Aleatorio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(btnListo)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnListo)
                    .addComponent(jButton1))
                .addContainerGap(746, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        GrafoMatriz g = crearGrafo();
        if(!g.isConnected(g, sistema.getTablero().getGrafo().getMax())){
            JOptionPane.showMessageDialog(this, "El grafo no es conexo", "Error", 0);
        }
        else{
            sistema.getTablero().setGrafo(g);
            new VentanaEscogerPersonajes(sistema).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnListoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crearGrafoAleatorio();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */

    
    public void generateTextFields(int size){
        int x = 0;
        int y = 0;
        for (int i = 0; i < size*size; i++){
            JTextField txf = new JTextField("");
            pnlPrincipal.add(txf);
            if(i<size){
                JLabel label2 = new JLabel(""+(i+1));
                pnlPrincipal.add(label2);
                label2.setLocation(20+20*y++, 20);
                label2.setSize(20, 20);
            }
            if (i%size == 0){
                x = 0;
                JLabel label = new JLabel(""+(i/size+1));
                pnlPrincipal.add(label);
                label.setLocation(20*x++, 40+i/size*20);
                label.setSize(20, 20);
            }
            txf.setText("0");
            txf.setLocation(20*x++, 40+i/size*20);
            txf.setSize(20, 20);
            textfields.add(txf);
        }
    }
    
    public GrafoMatriz crearGrafo(){
        GrafoMatriz g = new GrafoMatriz(sistema.getTablero().getGrafo().getMax());
        for (int i = 0; i < sistema.getTablero().getGrafo().getMax(); i++){
            g.agregarVertice(i+1);
        }
        for (int i = 0; i < sistema.getTablero().getGrafo().getMax()*sistema.getTablero().getGrafo().getMax(); i++) {
            if(Integer.parseInt(textfields.get(i).getText())!=1){
            }
            else{
                g.agregarArista(g.vertices[i%sistema.getTablero().getGrafo().getMax()], g.vertices[i/sistema.getTablero().getGrafo().getMax()]);
            }
        }
        g.imprimir();
            
        return g;
    }
    
    public void crearGrafoAleatorio(){
        for (int i = 0; i < sistema.getTablero().getGrafo().getMax()*sistema.getTablero().getGrafo().getMax(); i++) {
            Random random = new Random();
            int xd = random.nextInt(2);
            textfields.get(i).setText(xd+"");
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
